name: Update README

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          CONFIG_FILE: "./.github/recent-activity.config.yml"

      - uses: actions-js/profile-readme@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          username: Anirudh-A-V
          template: "TEMPLATE.md"

      - uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: "master"

